"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['jbuddy.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'icons/active_icon/jbuddy_active.icns',
    'plist': {
        'CFBundleIdentifier': 'com.jbuddy.app',
        'LSUIElement': True,  # This makes it a background app with no dock icon
        'CFBundleName': 'JBuddy',
        'CFBundleDisplayName': 'JBuddy',
        'CFBundleGetInfoString': 'Keep Teams active during working hours',
        'CFBundleVersion': '1.2.0',
        'CFBundleShortVersionString': '1.2.0',
    },
    'resources': ['icons/active_icon/jbuddy_active.icns', 'icons/idle_icon/jbuddy_idle.icns']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
